// contrib/views/storm/src/main/resources/scripts/components/Breadcrumbs.jsx
/**
 Licensed to the Apache Software Foundation (ASF) under one
 or more contributor license agreements.  See the NOTICE file
 distributed with this work for additional information
 regarding copyright ownership.  The ASF licenses this file
 to you under the Apache License, Version 2.0 (the
 "License"); you may not use this file except in compliance
 with the License.  You may obtain a copy of the License at
*
     http://www.apache.org/licenses/LICENSE-2.0
*
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/

define(['react',
 'react-dom'],
 function(React, ReactDOM) {
	'use strict';
    return React.createClass({
		displayName: 'Breadcrumbs',
        propTypes: {
            links: React.PropTypes.array.isRequired
        },
		getInitialState: function() {
			return null;
		},
		render: function() {			
			return (
				<ol id="breadcrumb">
					{this.renderLinks()}					
				</ol>
			);
    	},
    	renderLinks: function() {
    		var links = [];
    		for(var i = 0; i < this.props.links.length; i++){
    			var object = this.props.links[i];
    			if(object.link === '#!/dashboard'){
    				object.title = <i className="fa fa-home"></i>
    			}
    			links.push(<li key={i}><a href={object.link}>{object.title}</a></li>);
    		}    		
			return links;
    	}
    }); 
});

// ambari-logsearch/ambari-logsearch-web/src/app/components/breadrumbs/breadcrumbs.component.ts
/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import {Component, Input, OnDestroy, OnInit} from '@angular/core';
import {Subscription} from 'rxjs/Subscription';
import {ActivatedRouteSnapshot, Router, RoutesRecognized} from '@angular/router';

export interface BreadCrumb {
  text: string;
  path: string[];
}

@Component({
  selector: 'breadcrumbs',
  templateUrl: './breadcrumbs.component.html',
  styleUrls: ['./breadcrumbs.component.less']
})
export class BreadcrumbsComponent implements OnInit, OnDestroy {

  private subscriptions: Subscription[] = [];

  private crumbs: BreadCrumb[];

  @Input()
  addRootFirst: boolean = true;

  constructor(private router: Router) { }

  ngOnInit() {
    this.subscriptions.push(
      this.router.events.filter((event) => event instanceof RoutesRecognized).subscribe(this.onRoutesRecognized)
    );
  }

  ngOnDestroy() {
    this.subscriptions.forEach((subscription: Subscription) => subscription.unsubscribe());
  }

  getCrumbsFromRouterStateSnapshot(routerStateSnapshot: ActivatedRouteSnapshot): BreadCrumb[] {
    let level = routerStateSnapshot;
    const path: string[] = [];
    const breadcrumbs: BreadCrumb[] = [];
    while (level) {
      if (level.url.length) {
        path.push(
          (level.parent ? '' : '/') // start with trailng slash if this is the root
          + level.url.reduce((url, segment) => url += ('/' + segment.path), '') // build up the url by its segments
        );
        if (level.data.breadcrumbs) {
          let crumbs = level.data.breadcrumbs;
          if (!Array.isArray(crumbs)) {
            crumbs = [crumbs];
          }
          crumbs.forEach(breadcrumbTitle => breadcrumbs.push({
            text: breadcrumbTitle,
            path: path
          }));
        }
      }
      level = level.firstChild;
    }
    return breadcrumbs;
  }

  onRoutesRecognized = (routes: RoutesRecognized): void => {
    this.crumbs = this.getCrumbsFromRouterStateSnapshot(routes.state.root);
  }

}

<!--
  Licensed to the Apache Software Foundation (ASF) under one or more
  contributor license agreements.  See the NOTICE file distributed with
  this work for additional information regarding copyright ownership.
  The ASF licenses this file to You under the Apache License, Version 2.0
  (the "License"); you may not use this file except in compliance with
  the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->
<div class="breadcrumbs">
  <h4>
    <a *ngIf="addRootFirst" routerLink="/">{{'common.title' | translate}}</a>
    <ng-container *ngIf="crumbs && crumbs.length">
      <span *ngIf="crumbs.length" class="breadcrumb-separator">/</span>
      <ng-container *ngFor="let crumb of crumbs; index as i">
        <a *ngIf="i < crumbs.length-1" [routerLink]="crumb.path" routerLinkActive="active">{{crumb.text | translate}}</a>
        <span *ngIf="i === crumbs.length-1" class="breadcrumb-current">{{crumb.text | translate}}</span>
        <span *ngIf="i < crumbs.length-1" class="breadcrumb-separator">/</span>
      </ng-container>
    </ng-container>
  </h4>
</div>
