// ambari-logsearch/ambari-logsearch-web/src/app/modules/shared/components/modal/modal.component.ts
/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {Component, OnInit, AfterViewInit, ElementRef, Input, Output, ContentChild, TemplateRef, EventEmitter} from '@angular/core';
import * as $ from 'jquery';

@Component({
  selector: 'modal',
  templateUrl: './modal.component.html',
  styleUrls: ['./modal.component.less']
})
export class ModalComponent implements OnInit, AfterViewInit {

  constructor(private element: ElementRef) {
    this.rootElement = $(element.nativeElement);
  }

  ngOnInit() {
    this.modalElements = this.rootElement.find('.in');
    this.show();
  }

  ngAfterViewInit() {
    this.init.emit();
  }

  private rootElement: JQuery;

  private modalElements: JQuery;

  @Input()
  showHeader: boolean = true;

  @Input()
  title: string = '';

  @Input()
  showCloseButton: boolean = true;

  @Input()
  bodyText: string = '';

  @Input()
  showFooter: boolean = true;

  @Input()
  showSubmitButton: boolean = true;

  @Input()
  submitButtonLabel: string = 'modal.submit';

  @Input()
  submitButtonClassName: string = 'btn-success';

  @Input()
  showCancelButton: boolean = true;

  @Input()
  cancelButtonLabel: string = 'modal.cancel';

  @Input()
  cancelButtonClassName: string = 'btn-default';

  @Input()
  isSmallModal: boolean = false;

  @Input()
  isLargeModal: boolean = false;

  @Input()
  isExtraLargeModal: boolean = false;

  @Input()
  isSubmitDisabled: boolean = false;

  @ContentChild(TemplateRef)
  bodyTemplate;

  @Output()
  init: EventEmitter<any> = new EventEmitter();

  @Output()
  submit: EventEmitter<any> = new EventEmitter();

  @Output()
  cancel: EventEmitter<any> = new EventEmitter();

  @Output()
  close: EventEmitter<any> = new EventEmitter();

  @Input()
  isFlexLayout: boolean = false;

  show(): void {
    this.modalElements.show();
  }

  hide(): void {
    this.modalElements.hide();
  }

  onSubmit(): void {
    this.hide();
    this.submit.emit();
  }

  onCancel(): void {
    this.hide();
    this.cancel.emit();
  }

  onClose(): void {
    this.hide();
    this.close.emit();
  }

}

<!--
  Licensed to the Apache Software Foundation (ASF) under one or more
  contributor license agreements.  See the NOTICE file distributed with
  this work for additional information regarding copyright ownership.
  The ASF licenses this file to You under the Apache License, Version 2.0
  (the "License"); you may not use this file except in compliance with
  the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->

<div class="modal-backdrop in"></div>
<div class="modal in">
  <div [ngClass]="{
    'modal-dialog': true, 'modal-sm': isSmallModal, 'modal-lg': isLargeModal, 'modal-xl': isExtraLargeModal,
    'modal-flex-layout': isFlexLayout
  }">
    <div class="modal-content">
      <div *ngIf="showHeader" class="modal-header">
        <button *ngIf="showCloseButton" type="button" class="close" data-dismiss="modal" (click)="onClose()">
          <span class="fa fa-times"></span>
        </button>
        <h4 *ngIf="title">{{title}}</h4>
      </div>
      <div class="modal-body">
        <div *ngIf="bodyText">{{bodyText}}</div>
        <ng-template *ngIf="bodyTemplate" [ngTemplateOutlet]="bodyTemplate"></ng-template>
      </div>
      <div *ngIf="showFooter" class="modal-footer">
        <button *ngIf="showCancelButton" class="btn {{cancelButtonClassName}}"
                (click)="onCancel()">{{cancelButtonLabel | translate}}</button>
        <button *ngIf="showSubmitButton" class="btn {{submitButtonClassName}}"
                [attr.disabled]="isSubmitDisabled ? 'disabled' : null"
                (click)="onSubmit()">{{submitButtonLabel | translate}}</button>
      </div>
    </div>
  </div>
</div>

// contrib/views/storm/src/main/resources/scripts/components/Modal.jsx
/**
 Licensed to the Apache Software Foundation (ASF) under one
 or more contributor license agreements.  See the NOTICE file
 distributed with this work for additional information
 regarding copyright ownership.  The ASF licenses this file
 to you under the Apache License, Version 2.0 (the
 "License"); you may not use this file except in compliance
 with the License.  You may obtain a copy of the License at
*
     http://www.apache.org/licenses/LICENSE-2.0
*
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/

define(['react', 'react-dom', 'bootstrap'], function(React, ReactDOM) {
	'use strict';
	return React.createClass({
		displayName: 'Modal',
		getInitialState: function(){
			
			return null;
		},
		componentDidUpdate: function(){
			
		},
		componentDidMount: function(){

		},
		render: function() {
			return (
				<div className="modal fade" id={this.props.modalId} role="dialog">
				    <div className="modal-dialog">
				      	<div className="modal-content">
				        	<div className="modal-header">
				          		<button type="button" className="close" data-dismiss="modal">&times;</button>
				          		<h4 className="modal-title">{this.props.header ? <this.props.header /> : null}</h4>
				        	</div>
			        		<div className="modal-body">
				          		{this.props.content ? <this.props.content /> : null}
				        	</div>
				        	<div className="modal-footer">
				          		{this.props.footer ? <this.props.footer /> : <button type="button" className="btn btn-default" data-dismiss="modal">Close</button>}
				        	</div>
				      	</div>
				    </div>
				</div>
			);
		},
	});
});
