// ambari-logsearch/ambari-logsearch-web/src/app/components/login-form/login-form.component.ts
/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {Component} from '@angular/core';
import {Response} from '@angular/http';
import 'rxjs/add/operator/finally';
import {AppStateService} from '@app/services/storage/app-state.service';
import {AuthService} from '@app/services/auth.service';
import {Observable} from 'rxjs/Observable';

@Component({
  selector: 'login-form',
  templateUrl: './login-form.component.html',
  styleUrls: ['./login-form.component.less']
})
export class LoginFormComponent {

  username: string;

  password: string;

  isLoginAlertDisplayed: boolean;

  isLoginInProgress$: Observable<boolean> = this.appState.getParameter('isLoginInProgress');

  constructor(private authService: AuthService, private appState: AppStateService) {}

  /**
   * Handling the response from the login action. Actually the goal only to show or hide the login error alert.
   * When it gets error response it shows.
   * @param {Response} resp
   */
  private onLoginError = (resp: Response): void => {
    this.isLoginAlertDisplayed = true;
  }

  /**
   * Handling the response from the login action. Actually the goal only to show or hide the login error alert.
   * When it gets success response it hides.
   * @param {Response} resp
   */
  private onLoginSuccess = (resp: Response): void => {
    this.isLoginAlertDisplayed = false;
  }

  login() {
    this.authService.login(this.username, this.password).subscribe(this.onLoginSuccess, this.onLoginError);
  }

}

<!--
  Licensed to the Apache Software Foundation (ASF) under one or more
  contributor license agreements.  See the NOTICE file distributed with
  this work for additional information regarding copyright ownership.
  The ASF licenses this file to You under the Apache License, Version 2.0
  (the "License"); you may not use this file except in compliance with
  the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->

<div class="login-form well col-md-4 col-md-offset-4 col-sm-offset-4">
  <div class="alert alert-danger" *ngIf="isLoginAlertDisplayed" [innerHTML]="'authorization.error' | translate"></div>
  <form #loginForm="ngForm" (ngSubmit)="login()">
    <div class="form-group">
      <label for="username">{{'authorization.name' | translate}}</label>
      <input class="form-control" type="text" id="username" name="username" required [(ngModel)]="username">
    </div>
    <div class="form-group">
      <label for="password">{{'authorization.password' | translate}}</label>
      <input class="form-control" type="password" id="password" name="password" required [(ngModel)]="password">
    </div>
    <button class="btn btn-success" [disabled]="!loginForm.form.valid || (isLoginInProgress$ | async)">
      {{'authorization.signIn' | translate}}
    </button>
  </form>
</div>

// ambari-admin/src/main/resources/ui/ambari-admin/src/components/LoginForm/index.tsx
/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React, { useState, useRef, useEffect } from 'react';
import { Form, Button, Alert } from 'react-bootstrap';
import './LoginForm.scss';

interface LoginFormProps {
  onSubmit: (username: string, password: string) => Promise<void>;
  isSubmitting: boolean;
  errorMessage?: string;
}

interface ValidationErrors {
  username?: string;
  password?: string;
}

const LoginForm: React.FC<LoginFormProps> = ({ 
  onSubmit, 
  isSubmitting, 
  errorMessage 
}) => {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [validationErrors, setValidationErrors] = useState<ValidationErrors>({});
  const [touched, setTouched] = useState({ username: false, password: false });
  const usernameInputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    // Focus the username input when the component mounts
    if (usernameInputRef.current) {
      usernameInputRef.current.focus();
    }
  }, []);

  const validateForm = (): boolean => {
    const errors: ValidationErrors = {};
    
    if (!username.trim()) {
      errors.username = 'Username is required';
    }
    
    if (!password) {
      errors.password = 'Password is required';
    } else if (password.length < 4) {
      errors.password = 'Password must be at least 4 characters';
    }
    
    setValidationErrors(errors);
    return Object.keys(errors).length === 0;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    // Mark all fields as touched to show validation errors
    setTouched({ username: true, password: true });
    
    if (validateForm()) {
      await onSubmit(username, password);
    }
  };

  const handleBlur = (field: 'username' | 'password') => {
    setTouched({ ...touched, [field]: true });
    validateForm();
  };

  return (
    <div className="login-form">
      <h2>Sign in</h2>
      
      {errorMessage && (
        <Alert variant="danger" data-qa="login-error">
          {errorMessage}
        </Alert>
      )}
      
      <Form onSubmit={handleSubmit} noValidate>
        <Form.Group className="mb-3">
          <Form.Label data-qa="username-label">Username</Form.Label>
          <Form.Control
            type="text"
            value={username}
            onChange={(e) => setUsername(e.target.value)}
            onBlur={() => handleBlur('username')}
            isInvalid={touched.username && !!validationErrors.username}
            disabled={isSubmitting}
            ref={usernameInputRef}
            data-qa="username-input"
            className="login-username"
          />
          <Form.Control.Feedback type="invalid">
            {validationErrors.username}
          </Form.Control.Feedback>
        </Form.Group>
        
        <Form.Group className="mb-3">
          <Form.Label data-qa="password-label">Password</Form.Label>
          <Form.Control
            type="password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            onBlur={() => handleBlur('password')}
            isInvalid={touched.password && !!validationErrors.password}
            disabled={isSubmitting}
            data-qa="password-input"
            className="login-password"
            autoComplete="new-password"
            onKeyDown={(e) => {
              if (e.key === 'Enter') {
                handleSubmit(e);
              }
            }}
          />
          <Form.Control.Feedback type="invalid">
            {validationErrors.password}
          </Form.Control.Feedback>
        </Form.Group>
        
        <Button
          variant="success"
          type="submit"
          disabled={isSubmitting}
          data-qa="login-button"
          className="sign-in-button"
        >
          {isSubmitting ? 'SIGNING IN...' : 'SIGN IN'}
        </Button>
      </Form>
    </div>
  );
};

export default LoginForm;
