// ambari-web/latest/src/components/Modal.tsx
/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { Button, Modal as ReactModal } from "react-bootstrap";
import DefaultButton from "./DefaultButton";
import { ReactNode } from "react";

export type ModalProps = {
  isOpen: boolean;
  onClose: () => void;
  modalTitle: string;
  modalBody: ReactNode;
  className?:string;
  successCallback: () => void;
  options: {
    modalSize?: string;
    shouldShowFooter?: boolean;
    buttonSize?: "sm" | "lg" | undefined;
    okButtonText?: string;
    cancelButtonText?: string;
    cancelableViaIcon?: boolean;
    cancelableViaBtn?: boolean;
    cancelableViaSuccessBtn?: boolean;
    okButtonVariant?: string;
    okButtonDisabled?: boolean;
    extraButtons?: {
      text: string;
      onClick: () => void;
      variant?: string;
      order?: number;
      [key: string]: any;
    }[];
  };
};

export default function Modal({
  isOpen,
  onClose,
  modalTitle,
  modalBody,
  successCallback,
  options,
  className
}: ModalProps) {
  const {
    modalSize = "modal-width", //Other options are modal-sm, modal-md, modal-lg - Change via prop
    shouldShowFooter = true,
    buttonSize = undefined, //Other options are sm, lg - Change via prop (undefined or any other string will be considered as default size i.e. medium)
    okButtonText = "OK",
    cancelButtonText = "CANCEL",
    cancelableViaIcon = false,
    cancelableViaBtn = true,
    okButtonVariant = "success",
    cancelableViaSuccessBtn = true,
    okButtonDisabled = false,
    extraButtons = [],
  } = options;

  const sortedExtraButtons = Array.isArray(extraButtons)
    ? extraButtons.sort((a: any, b: any) => (a.order || 0) - (b.order || 0))
    : [];

  return (
    <ReactModal
      show={isOpen}
      onHide={onClose}
      className={
        `custom-modal-container make-scrollable custom-scrollbar ${className} ` +
        modalSize
      }
      data-testid="confirmation-modal"
    >
      <ReactModal.Header closeButton={cancelableViaIcon}>
        <ReactModal.Title>
          <h2>{modalTitle}</h2>
        </ReactModal.Title>
      </ReactModal.Header>
      <ReactModal.Body>
        <div className="pre-wrap">{modalBody}</div>
      </ReactModal.Body>
      {!shouldShowFooter ? null : (
        <ReactModal.Footer className="d-flex justify-content-end">
          {cancelableViaBtn ? (
            <DefaultButton
              size={buttonSize}
              className="ps-3 pe-3 text-white"
              onClick={onClose}
              data-testid="confirm-cancel-btn"
            >
              {cancelButtonText}
            </DefaultButton>
          ) : null}
          {sortedExtraButtons.map((button: any) => (
            <Button
              key={button.text}
              className="ps-3 pe-3 text-white custom-btn"
              variant={button.variant}
              onClick={button.onClick}
              size={buttonSize}
              {...button}
            >
              {button.text}
            </Button>
          ))}
          {cancelableViaSuccessBtn ? (
            <Button
              className={`ps-3 pe-3 text-white custom-btn ${
                okButtonDisabled ? "disabled-btn" : ""
              }`}
              variant={okButtonVariant}
              onClick={successCallback}
              size={buttonSize}
              data-testid="confirm-ok-btn"
              disabled={okButtonDisabled}
            >
              {okButtonText}
            </Button>
          ) : null}
        </ReactModal.Footer>
      )}
    </ReactModal>
  );
}

// ambari-logsearch/ambari-logsearch-web-new/src/app/components/modal/modal.component.ts
/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {Component, OnInit, AfterViewInit, ElementRef, Input, Output, ContentChild, TemplateRef, EventEmitter} from '@angular/core';
import * as $ from 'jquery';

@Component({
  selector: 'modal',
  templateUrl: './modal.component.html'
})
export class ModalComponent implements OnInit, AfterViewInit {

  constructor(private element: ElementRef) {
    this.rootElement = $(this.element.nativeElement);
  }

  ngOnInit() {
    this.modalElements = this.rootElement.find('.in');
    this.show();
  }

  ngAfterViewInit() {
    this.init.emit();
  }

  private rootElement: JQuery;

  private modalElements: JQuery;

  @Input()
  showHeader: boolean = true;

  @Input()
  title: string = '';

  @Input()
  showCloseButton: boolean = true;

  @Input()
  bodyText: string = '';

  @Input()
  showFooter: boolean = true;

  @Input()
  showSubmitButton: boolean = true;

  @Input()
  submitButtonLabel: string = 'modal.submit';

  @Input()
  submitButtonClassName: string = 'btn-success';

  @Input()
  showCancelButton: boolean = true;

  @Input()
  cancelButtonLabel: string = 'modal.cancel';

  @Input()
  cancelButtonClassName: string = 'btn-default';

  @Input()
  isSmallModal: boolean = false;

  @Input()
  isLargeModal: boolean = false;

  @ContentChild(TemplateRef)
  bodyTemplate;

  @Output()
  init: EventEmitter<any> = new EventEmitter();

  @Output()
  submit: EventEmitter<any> = new EventEmitter();

  @Output()
  cancel: EventEmitter<any> = new EventEmitter();

  @Output()
  close: EventEmitter<any> = new EventEmitter();

  show(): void {
    this.modalElements.show();
  }

  hide(): void {
    this.modalElements.hide();
  }

  onSubmit(): void {
    this.hide();
    this.submit.emit();
  }

  onCancel(): void {
    this.hide();
    this.cancel.emit();
  }

  onClose(): void {
    this.hide();
    this.close.emit();
  }

}

<!--
  Licensed to the Apache Software Foundation (ASF) under one or more
  contributor license agreements.  See the NOTICE file distributed with
  this work for additional information regarding copyright ownership.
  The ASF licenses this file to You under the Apache License, Version 2.0
  (the "License"); you may not use this file except in compliance with
  the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->

<div class="modal-backdrop in"></div>
<div class="modal in">
  <div [ngClass]="{'modal-dialog': true, 'modal-sm': isSmallModal, 'modal-lg': isLargeModal}">
    <div class="modal-content">
      <div *ngIf="showHeader" class="modal-header">
        <button *ngIf="showCloseButton" type="button" class="close" data-dismiss="modal" (click)="onClose()">
          <span>&times;</span>
        </button>
        <h4 *ngIf="title">{{title}}</h4>
      </div>
      <div class="modal-body">
        <div *ngIf="bodyText">{{bodyText}}</div>
        <ng-template *ngIf="bodyTemplate" [ngTemplateOutlet]="bodyTemplate"></ng-template>
      </div>
      <div *ngIf="showFooter" class="modal-footer">
        <button *ngIf="showCancelButton" class="btn {{cancelButtonClassName}}"
                (click)="onCancel()">{{cancelButtonLabel | translate}}</button>
        <button *ngIf="showSubmitButton" class="btn {{submitButtonClassName}}"
                (click)="onSubmit()">{{submitButtonLabel | translate}}</button>
      </div>
    </div>
  </div>
</div>
